version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: sh /myapp/init.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: /myapp
    stdin_open: true
    tty: true